### PR TITLE
fix xpath

### PR DESCRIPTION
**Pull request by lublak**

### CODE REVIEW

**Comment by Niek** [comment]
Which issue does this fix?

**Comment by Niek** [comment]
What problem exactly?

**Comment by lublak** [comment]
@Niek 
```
uncaughtException: Cannot read properties of undefined (reading 'remoteObject')
TypeError: Cannot read properties of undefined (reading 'remoteObject')
    at Object.<anonymous> (D:\n8n-nodes-documentation-builder\node_modules\ghost-cursor\lib\spoof.js:458:61)
    at step (D:\n8n-nodes-documentation-builder\node_modules\ghost-cursor\lib\spoof.js:44:23)
    at Object.next (D:\n8n-nodes-documentation-builder\node_modules\ghost-cursor\lib\spoof.js:25:53)
    at fulfilled (D:\n8n-nodes-documentation-builder\node_modules\ghost-cursor\lib\spoof.js:16:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Niek** [comment]
Thanks, I added an XPath test now and merged a slightly modified version

**Comment by lublak** [comment]
@Niek thanks 👍 :)

**Pull request closed without merging**
