### PR TITLE
ChatGPT generated methods documentation

### PR DESCRIPTION
**Pull request by TheGP**
I was very surprised there is no documentation on any of the methods.

### CODE REVIEW

**Comment by Niek** [comment]
Fixes #13

**Comment by Niek** [comment]
Make sure to add `hesitate` to the docs too :)

**Comment by Niek** [comment]
Fixes #112

**Comment by TheGP** [comment]
Did some manual checks: added hesitate, fixed click options, and added a small example and a remark.

**Comment by Niek** [comment]
Thanks @TheGP - merged now!

**Comment by AndriusCTR** [comment]
> Fixes #13

Is this a random delay? If it's fixed then it's the same as no delay... definitely need to have random number

**Pull request merged**
