### PR TITLE
Associated timestamps with movements for further authenticity

### PR DESCRIPTION
**Pull request by aw1875**
Modified the path return values to also include a random timestamp between 2 and 5 seconds as an added layer of authenticity. Super useful for tasks like hcaptcha requests.

### CODE REVIEW

**Comment by Niek** [comment]
Great work! Small request: can you switch to using `yarn` instead of `npm`? So we don't need `package-lock.json` and also the formatting will be fixed right away.

**Comment by aw1875** [comment]
@Niek I've never used yarn but I would have no problems making that switch! And yes sorry it looks like prettifier automatically changed a ton of formatting when I saved. What changes do I need to make to use yarn?

**Comment by Niek** [comment]
> @Niek I've never used yarn but I would have no problems making that switch! And yes sorry it looks like prettifier automatically changed a ton of formatting when I saved. What changes do I need to make to use yarn?

No worries, just install yarn and run `yarn`, it will lint the files correctly.

**Comment by aw1875** [comment]
Just pushed the changes with yarn!

**Comment by aw1875** [comment]
@Niek looks like the yarn lock has conflicting node versions is there any way to fix that (again sorry I'm new to yarn)

**Pull request closed without merging**
