### PR TITLE
Fix to get correct inline element position

### PR DESCRIPTION
**Pull request by kbourro**
Some elements like <a> split in multiple lines at small screens.

### CODE REVIEW

**Comment by Niek** [comment]
Do you have a test case/URL? Because if it's really a bug with some elements it might require fixing upstream in [elementHandle.boundingBox()](https://pptr.dev/#?product=Puppeteer&show=api-elementhandleboundingbox).

**Comment by kbourro** [comment]
Check the following screenshot.
https://i.gyazo.com/473ab1bd5666715460cfcfd2f2d7c28c.png
Even in chrome the box is not the clickable element. So mouse click fails.

**Comment by kbourro** [comment]
@Niek did you have time to check it ?

**Comment by Niek** [comment]
Do you have a HTML sample? I have a hard time finding a test case to check this issue.

**Comment by kbourro** [comment]
https://www.reddit.com/user/kbourro/comments/ja9kac/%CE%BA%CE%BB%CE%B5%CE%B9%CE%B4%CE%B1%CF%81%CE%AC%CF%82_%CF%83%CF%84%CE%BF_%CE%BA%CE%B5%CF%81%CE%B1%CF%84%CF%83%CE%AF%CE%BD%CE%B9/
Emulate as Pixel 2 and try to click the following a element
https://i.gyazo.com/eb674413d44082cdc6660288b6b23ba5.png

**Comment by Niek** [comment]
I did some checks, I prefer this method as it's safer (no leaks):

```javascript
const puppeteer = require('puppeteer');
puppeteer
  .launch()
})
  .then(async browser => {
    const page = await browser.newPage();
    await page.goto(
      'https://old.reddit.com/user/kbourro/comments/ja9kac/%CE%BA%CE%BB%CE%B5%CE%B9%CE%B4%CE%B1%CF%81%CE%AC%CF%82_%CF%83%CF%84%CE%BF_%CE%BA%CE%B5%CF%81%CE%B1%CF%84%CF%83%CE%AF%CE%BD%CE%B9/',
    );
    const el = await page.waitForSelector('form > div > div > p:nth-child(2) > a');
    const quads = await page._client.send('DOM.getContentQuads', { objectId: el._remoteObject.objectId });
    console.log(quads);
    await browser.close();
  });
/* output:
{
  quads: [
    [
       151.09375, 293.265625,
      456.546875, 293.265625,
      456.546875, 310.265625,
       151.09375, 310.265625
    ],
    [
       151.09375, 313.265625,
      781.640625, 313.265625,
      781.640625, 330.265625,
       151.09375, 330.265625
    ]
  ]
}
*/
```

**Comment by kbourro** [comment]
First you need to emulate the device as pixel 2 so the a element will split in two lines. I will test getContentQuads

**Comment by kbourro** [comment]
Check the latest commit

**Comment by Niek** [comment]
Works great, thanks! I will merge this.

It could be improved a little bit by not taking the first quad but by calculating the minimum rectangle-size that overlaps all quads. But we'll leave that for someone else to fix in his spare time ;)

**Pull request merged**
