### PR TITLE
style: minor style updates

### PR DESCRIPTION
**Pull request by bvandercar-vt**
these style changes are just my opinions based on common code practices I've seen-- you don't need to agree though! If you don't like any of these changes we can cancel the PR no big deal

### CODE REVIEW

**Comment by Niek** [comment]
Is this ready for matching @bvandercar-vt?

**Comment by bvandercar-vt** [comment]
@Niek Yep

**Comment by bvandercar-vt** [comment]
@Niek these style changes are just my opinions based on common code practices I've seen-- you don't need to agree though! If you don't like any of these changes we can cancel the PR no big deal

**Comment by Niek** [comment]
Merge, thanks!

**Pull request merged**
